version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: content_analytics_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: content_analytics
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
